### ISSUE TITLE
SickChill errors

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#154]
@OneCDOnly I still get errors:

>>>>>>>>>> datetime:'Wed Jul 14 15:56:28 CEST 2021',request:'starting',QPKG:'210714',app:'2021.4.10' <<<<<<<<<<
daemon: NOT active
file (/opt/bin/git): exists
update 'SickChill' from remote repository: OK
workaround (https://github.com/SickChill/SickChill/issues/7249): OK
disable auto-update: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/locale
/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/locale
Traceback (most recent call last):
  File "/share/ZFS3_DATA/.qpkg/SickChill/SickChill/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/share/ZFS530_DATA/.qpkg/SickChill/SickChill/lib3/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.9/site-packages/lxml/__init__.py)"
result: [1]

_Originally posted by @HazMatt69 in https://github.com/SickChill/SickChill/issues/7259#issuecomment-879916564_

**Comment by OneCDOnly** [comment]
@Hazmatt69 Looks like @miigotu has blocked me from the SickChill repo. What a jerk. 

Can you please reinstall Entware?
```
sherpa reinstall ew
```

**Comment by HazMatt69** [comment]
@OneCDOnly Sorry for your troubles... It's working again, thanks!

**Comment by OneCDOnly** [comment]
Great! :)
