### ISSUE TITLE
Medusa not starting

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#165]
```
[~] # /etc/init.d/omedusa.sh start
daemon: NOT active
file (/opt/bin/git): exists
update 'OMedusa' from remote repository: OK
current git branch: master
file (/opt/bin/python3): exists
load UI ports from application: OK
start daemon: failed!
= ExecuteAndLog()
output: "Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/__init__.py", line 24, in <module>
    initialize()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/init/__init__.py", line 37, in initialize
    _configure_guessit()
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/medusa/init/__init__.py", line 201, in _configure_guessit
    import guessit
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/__init__.py", line 8, in <module>
    from .api import guessit, GuessItApi
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/api.py", line 17, in <module>
    from .rules import rebulk_builder
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/__init__.py", line 11, in <module>
    from .properties.episodes import episodes
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/episodes.py", line 16, in <module>
    from .title import TitleFromPosition
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/title.py", line 11, in <module>
    from .language import (
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/guessit/rules/properties/language.py", line 10, in <module>
    import babelfish
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/__init__.py", line 20, in <module>
    from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/ext/babelfish/converters/__init__.py", line 6, in <module>
    from pkg_resources import iter_entry_points, EntryPoint
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/OMedusa/lib/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'"
result: [1]
```

**Comment by OU812-me2** [comment]
@OneCDOnly I am having this issue too. Happy to provide my logs or test potential solutions. Started when I typed upgrade all. Interestingly LazyLibrarian and SABnzbd also failed during this process. I was able to back up the configuration of these two, uninstall, install and then restore config, this brought process brought LazyLibrarian and SABnzbd back but not Medusa.

**Comment by OneCDOnly** [comment]
@OU812-me2 thank you. 

Good news! Looks like the develop branch now has a fix for this: https://github.com/pymedusa/Medusa/pull/10175

**Comment by OU812-me2** [comment]
Awesome!! I'll give it a try!

**Comment by OU812-me2** [comment]
@OneCDOnly upgrading to the new version of Medusa (via Master) fixed this issue, the fix (previously in develop) was merged up. So all programs are running now. NZBtoMedia now seems to be the issue when using it to post-process on Python 3.10.x

**Comment by OneCDOnly** [comment]
Confirmed: Medusa in the `master` branch is now working again with Python 3.10. 🎉
