### ISSUE TITLE
SABnzbd: SABYenc disabled: no correct version found! (Found v5.4.2, expecting v4.0.0)

### ISSUE THREAD

**Issue by abeumer** [OneCDOnly/sherpa#198]
I noticed that SABnzbd was giving me a error that SABYenc was "Not available"
Amongst the various things in trying to solve this I also tried reinstalling SABnzbd:
```
sudo sherpa reinstall SABnzbd
Password: 
sherpa 220629 • a mini-package-manager for QNAP NAS

done: installed 3 PIP groups                                            
done: reinstalled 1 dependent QPKG                                            
done: restarted 1 dependent QPKG
```
SABnzbd 3.5.2 is installed but that doesn't support SABYenc 5.4.2:
![SAB version](https://user-images.githubusercontent.com/22363701/178945930-398f71db-fcf9-4edb-b1c3-43f087a2caff.png)
SABYenc disabled: no correct version found! (Found v5.4.2, expecting v4.0.0)
![SAB error](https://user-images.githubusercontent.com/22363701/178945925-01024f2a-09fb-46b4-8994-9c7e5c2b51f7.png)

According to https://sabnzbd.org/wiki/installation/sabyenc.html
SABnzbd 3.5.x and lower only works with sabyenc3 version 4.0.x
SABnzbd 3.6.x and higher only works with sabyenc3 version 5.0.x

Somehow there are 2 versions of sabyenc3 present on my system but when I uninstall both and reinstall 4.0.2, it's not found.
I'm not entirely sure that this is the right place to ask this question but as sherpa seems to install the wrong version, I thought I'd start by asking here.

---------------------------
```
$ pip3 list
sabyenc3              4.0.2
```

```
$ pip3 uninstall sabyenc3
Found existing installation: sabyenc3 4.0.2
Uninstalling sabyenc3-4.0.2:
  Would remove:
    /share/CACHEDEV1_DATA/homes/nas-admin/.local/lib/python3.10/site-packages/sabyenc3-4.0.2-py3.10.egg-info
    /share/CACHEDEV1_DATA/homes/nas-admin/.local/lib/python3.10/site-packages/sabyenc3.cpython-310.so
Proceed (Y/n)? y
  Successfully uninstalled sabyenc3-4.0.2
```

```
$ pip3 list
sabyenc3              5.4.2
```

```
$ pip3 uninstall sabyenc3
Found existing installation: sabyenc3 5.4.2
Uninstalling sabyenc3-5.4.2:
  Would remove:
    /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages/sabyenc3-5.4.2-py3.10.egg-info
    /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages/sabyenc3.cpython-310.so
Proceed (Y/n)? y
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/lib/python3.10/shutil.py", line 813, in move
OSError: [Errno 18] Invalid cross-device link: '/share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages/sabyenc3-5.4.2-py3.10.egg-info' -> '/tmp/pip-uninstall-tg_8ot9j'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 98, in run
    uninstall_pathset = req.uninstall(
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 642, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 373, in remove
    moved.stash(path)
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 271, in stash
    renames(path, new_path)
  File "/share/homes/nas-admin/.local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 311, in renames
    shutil.move(old, new)
  File "/opt/lib/python3.10/shutil.py", line 831, in move
  File "/opt/lib/python3.10/shutil.py", line 722, in rmtree
  File "/opt/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
  File "/opt/lib/python3.10/shutil.py", line 676, in _rmtree_safe_fd
PermissionError: [Errno 13] Permission denied: 'top_level.txt'
```

```
$ sudo pip3 uninstall sabyenc3
Password: 
Found existing installation: sabyenc3 5.4.2
Uninstalling sabyenc3-5.4.2:
  Would remove:
    /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages/sabyenc3-5.4.2-py3.10.egg-info
    /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.10/site-packages/sabyenc3.cpython-310.so
Proceed (Y/n)? y
  Successfully uninstalled sabyenc3-5.4.2
WARNING: Running pip as the 'root' user can result in broken permissions ......
```

```
$ python3 -m pip install --force-reinstall --ignore-installed --no-binary :all: sabyenc3==4.0.2
Defaulting to user installation because normal site-packages is not writeable
Collecting sabyenc3==4.0.2
  Using cached sabyenc3-4.0.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... done
Skipping wheel build for sabyenc3, due to binaries being disabled for it.
Installing collected packages: sabyenc3
  Running setup.py install for sabyenc3 ... done
Successfully installed sabyenc3-4.0.2
```

Restarted SABnzbd
SABYenc: | Not available |

**Comment by OneCDOnly** [comment]
Hi @abeumer :)

Hmm, let's start by running a `clean` on your SABnzbd installation:
```
sherpa clean sab
```
... then run a `check`:
```
sherpa check
```
How's it look now?

**Comment by abeumer** [comment]
That seems to have fixed it.
```
$ sudo sherpa clean sab
Password: 
sherpa 220629 • a mini-package-manager for QNAP NAS

done: cleaned 1 dependent QPKG                                            

$ sudo sherpa check
sherpa 220629 • a mini-package-manager for QNAP NAS

done: installed 3 PIP groups                                            
done: restarted 1 dependent QPKG 
```
![Screenshot_20220720_111309](https://user-images.githubusercontent.com/22363701/179945198-178ff59c-08db-4480-80fe-bdff34e0d354.png)

It installed 3.6.0 and now I no longer get a SABYenc error.
Thank you!
