### ISSUE TITLE
bug: deluge applications not starting after upgrade

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#204]
Entware package list has just been updated, so now Deluge 2.1.1 is available. 
```
[~] # /etc/init.d/deluge-server.sh start
daemon: NOT active
file (/opt/bin/deluged): exists
start daemon: Traceback (most recent call last):
  File "/opt/bin/deluged", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.1.1', 'gui_scripts', 'deluged')())
  File "/opt/bin/deluged", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
OK
wait for (/var/run/Deluge-server.pid) to appear: (no-more than 5 seconds): 1, 2, 3, 4, 5, failed!
(/var/run/Deluge-server.pid) not found! (exceeded timeout: 5 seconds)
```
```
[~] # /etc/init.d/deluge-web.sh start
daemon: NOT active
file (/opt/bin/deluge-web): exists
load UI ports from application: OK
start daemon: Traceback (most recent call last):
  File "/opt/bin/deluge-web", line 33, in <module>
    sys.exit(load_entry_point('deluge==2.1.1', 'gui_scripts', 'deluge-web')())
  File "/opt/bin/deluge-web", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
OK
wait for (/var/run/Deluge-web.pid) to appear: (no-more than 5 seconds): 1, 2, 3, 4, 5, failed!
(/var/run/Deluge-web.pid) not found! (exceeded timeout: 5 seconds)
```

**Comment by OneCDOnly** [comment]
fixed here: https://github.com/OneCDOnly/sherpa/commit/b768ece7aedb9eb59e47350ca7956f086bd833e0
