### ISSUE TITLE
QNAP errors for `sherpa` and `OSickGear`

### ISSUE THREAD

**Issue by rivy** [OneCDOnly/sherpa#262]
I'm getting some odd errors from `sherpa` on my QNAP.

```shell
# sherpa
sherpa 230227-stable • a mini-package-manager for QNAP NAS

/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 1584: Args.Unknown.IsAny: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 798: Args.Unknown.IsNone: command not found
• Usage: sherpa [action] [packages] [package group] [options]

   To list available [action]s:
      # sherpa list actions

   To list available [packages]:
      # sherpa list packages
      # sherpa p

   To list available [package group]s:
      # sherpa list groups

   Or, for more [options]:
      # sherpa list options

• More in the wiki: https://github.com/OneCDOnly/sherpa/wiki
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsStarted.IsSet: command not found
```

I'm also seeing a request to change to the 'main' branch on 'OSickGear', but I'm unable to force the branch change. The configuration keeps getting rewritten to load only the 'master' branch when 'OSickGear' is reloaded.

Please let me know if there is more information I can supply or assistance I can give to help track down the issue.

Thanks for your excellent work on this over the years!!

**Comment by OneCDOnly** [comment]
Hey Roy. :)

Can you please execute a `sherpa reset` then see if sherpa runs correctly?

**Comment by OneCDOnly** [comment]
With regard to SickGear, the branch is set by the service-script. The current branch in the OSickGear `v230211a` QPKG is `main`. 

When sherpa is running again, can you please check which OSickGear QPKG version is installed?

**Comment by rivy** [comment]
👋🏻 
Thanks for the response. I'd tried the reset without success.
Here's a reproduction...

```shell
$ sherpa reset
done: all logs cleared
done: package cache cleared
$ sherpa
sherpa 230227-stable • a mini-package-manager for QNAP NAS

/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 1584: Args.Unknown.IsAny: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 798: Args.Unknown.IsNone: command not found
• Usage: sherpa [action] [packages] [package group] [options]

   To list available [action]s:
      # sherpa list actions

   To list available [packages]:
      # sherpa list packages
      # sherpa p

   To list available [package group]s:
      # sherpa list groups

   Or, for more [options]:
      # sherpa list options

• More in the wiki: https://github.com/OneCDOnly/sherpa/wiki
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsBackedUp.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsInstalled.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsMissing.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcBackup.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcClean.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcInstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReassign.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRebuild.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcReinstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestart.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcRestore.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStart.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcStop.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUninstall.IsStarted.IsSet: command not found
/share/CACHEDEV1_DATA/.qpkg/sherpa/cache/sherpa.manager.sh: line 3773: QPKGs.AcUpgrade.IsStarted.IsSet: command not found
```

Notably, I did have a reboot of the NAS recently due to power instability in the area during a recent storm.
The  reboot was a controlled shutdown and restart, and I'm not having any other issues.
I also tried re-installing `sherpa` from the QPKG without success.

I've not touched the NAS firmware in quite a while, is there some limitation there?

**Comment by rivy** [comment]
As for OSickGear...
I actually ran into the issue with `sherpa` while trying to see if `sherpa` had an update to correct the warning messages... 😄
Likely if I can get `sherpa` back in shape, I can solve that issue directly.

**Comment by OneCDOnly** [comment]
Yes, there's something wrong there. It looks like your sherpa loader isn't grabbing the latest sherpa management script. :confused:

I think this is because I recently shuffled the sherpa branches around. The old default was `main`, now it's called `stable`. But, it meant I had to release a new sherpa QPKG with an updated loader script to support this. I was hoping the old setup would continue to work until everyone had upgraded their sherpa QPKG - now, I'm not so-sure. 

Can you please download and manually install [this](https://github.com/OneCDOnly/sherpa/raw/stable/QPKGs/sherpa/build/sherpa_230227.qpkg) sherpa QPKG via your App Center? It will automatically overwrite your existing one. Then please log-out your SSH session, then login again. How does sherpa look now?

**Comment by rivy** [comment]
Will do...

**Comment by rivy** [comment]
Yes, that seemed to work.
I installed the referenced QPKG over the current one, issued a `sherpa reset`, and now I'm getting a normal response...

```shell
$ sherpa reset
done: all logs cleared
done: package cache cleared
$ sherpa
sherpa 230306-stable • a mini-package-manager for QNAP NAS

• Usage: sherpa [action] [packages] [package group] [options]

   To list available [action]s:
      # sherpa list actions

   To list available [packages]:
      # sherpa list packages
      # sherpa p

   To list available [package group]s:
      # sherpa list groups

   Or, for more [options]:
      # sherpa list options

• More in the wiki: https://github.com/OneCDOnly/sherpa/wiki
```

I've upgraded a couple of the packages; `inxi` and `NZBGet` upgraded just fine and seem to be working.

`LazyLibrarian` and `OMedusa` are being recalcitrant, but I don't really use those. So, I'll play with them a bit to see if I can get them to restart successfully.

There's an upgrade available for `OSickGear` as well; I'm going to wait a bit on that as it's working fine and busily downloading a couple of shows at the moment.

Thanks for your incredibly fast response and help!
And thanks for the incredibly nice work that you've given to us!! 🚀✨

If you need anything in the future, I'd be happy to help.

**Comment by OneCDOnly** [comment]
Thanks Roy, my apologies for the trouble.

Please advise if you need any further help too.  I appreciate your patience.

Cheers!

**Comment by rivy** [comment]
Hmm, looks like both LazyLibrarian and OMedusa are being tripped up by the same OpenSSL python problem.

```text
start daemon: dbug: (LL)
dbug: (LL) adding external log to main log ...
dbug: (LL) ----------------------------------------------------------------------------------------------------
dbug: (LL) = log file: '/var/log/DisplayRunAndLog_h0zGBh'
dbug: (LL) command: '. /share/CACHEDEV1_DATA/.qpkg/OMedusa/venv/bin/activate && cd /share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache && /share/CACHEDEV1_DATA/.qpkg/OMedusa/venv/bin/python3 /share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/start.py --daemon --nolaunch --datadir /share/CACHEDEV1_DATA/.qpkg/OMedusa/config --config /share/CACHEDEV1_DATA/.qpkg/OMedusa/config/config.ini --pidfile /var/run/OMedusa.pid'
dbug: (LL) ! result_code: [1] ***** stdout/stderr begins below *****
dbug: (LL) Traceback (most recent call last):
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/start.py", line 6, in <module>
dbug: (LL) from medusa.__main__ import main
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/medusa/__main__.py", line 67, in <module>
dbug: (LL) from medusa import (
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/medusa/helpers/__init__.py", line 49, in <module>
dbug: (LL) from medusa.session.core import MedusaSafeSession
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/medusa/session/core.py", line 14, in <module>
dbug: (LL) from medusa. Session import factory, handlers, hooks
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/medusa/session/handlers.py", line 9, in <module>
dbug: (LL) from cloudscraper import CloudScraper
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/cloudscraper/__init__.py", line 14, in <module>
dbug: (LL) from requests_toolbelt.utils import dump
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/requests_toolbelt/__init__.py", line 12, in <module>
dbug: (LL) from .adapters import SSLAdapter, SourceAddressAdapter
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/requests_toolbelt/adapters/__init__.py", line 12, in <module>
dbug: (LL) from .ssl import SSLAdapter
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/requests_toolbelt/adapters/ssl.py", line 16, in <module>
dbug: (LL) from .._compat import poolmanager
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/requests_toolbelt/_compat.py", line 56, in <module>
dbug: (LL) from requests.packages.urllib3.contrib.pyopenssl \
dbug: (LL) File "/share/CACHEDEV1_DATA/.qpkg/OMedusa/repo-cache/ext/urllib3/contrib/pyopenssl.py", line 46, in <module>
dbug: (LL) import OpenSSL.SSL
dbug: (LL) File "/opt/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
dbug: (LL) File "/opt/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3279, in <module>
dbug: (LL) AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'
dbug: (LL) = ***** stdout/stderr is complete *****
dbug: (LL) ----------------------------------------------------------------------------------------------------
failed!
```

There are a couple of discussions about the problem: <https://levelup.gitconnected.com/fix-attributeerror-module-lib-has-no-attribute-openssl-521a35d83769> , <https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss> , and <https://github.com/pyca/cryptography/issues/7959>.

I couldn't use suggested fix of `pip install openssl>22.1.0`:

```text
ERROR: Could not find a version that satisfies the requirement openssl (from versions: none)
ERROR: No matching distribution found for openssl
```

but, it's fixed (at least temporarily) with the alternative suggestion of `pip install cryptography==38.0.4`.

Hopefully, that will help if others encounter the issue or it crops up with later upgrades.

**Comment by OneCDOnly** [comment]
Ah, this looks like a case where we are limited by the `pyopenssl` version available via Entware. 

pyOpenSSL turns-out to be one of those modules we can't install locally in each NAS via `pip` (due to compilation errors), so we must use the existing Entware IPK package called `python3-pyopenssl`. This is presently at v21.0.0. and is installed as a system-wide Python package. Your local application virtualenvs for Medusa, SickGear, SABnzbd, etc... have access to it, but they can't upgrade it. 

I like that specific cryptography version suggestion. I may have to hardcode that into the affected QPKG's service-scripts to ensure `pip` installs only v38.0.4. 

Please let me know if this sounds correct, or if I've misunderstood your solution.

**Comment by rivy** [comment]
> Ah, this looks like a case where we are limited by the `pyopenssl` version available via Entware.
> 
> pyOpenSSL turns-out to be one of those modules we can't install locally in each NAS via `pip` (due to compilation errors), so we must use the existing Entware IPK package called `python3-pyopenssl`. This is presently at v21.0.0. and is installed as a system-wide Python package. Your local application virtualenvs for Medusa, SickGear, SABnzbd, etc... have access to it, but they can't upgrade it.
> 
> I like that specific cryptography version suggestion. I may have to hardcode that into the affected QPKG's service-scripts to ensure `pip` installs only v38.0.4.
> 
> Please let me know if this sounds correct, or if I've misunderstood your solution.

Yep, that's exactly correct, `pip install cryptography==38.0.4` fixes the startup error for both applications/packages.
I haven't upgraded `OSickGear` or `SABnzbd` as of yet to test them.

**Comment by OneCDOnly** [comment]
Can I confirm: did you install `cryptography` inside each application's virtualenv, or outside it? 

- Inside would require you to source each apps `activate` script before running `pip`. 

- Outside would run the system-wide `pip` available via Entware. 

Also, what is your NAS model and QTS version please?

**Comment by OneCDOnly** [comment]
A quick follow-up on a couple of issues we've discussed in this topic. 

I've updated the sherpa QPKG that users download by-default from the [latest releases GitHub page](https://github.com/OneCDOnly/sherpa/releases/tag/v230227). This one will work just fine with the new branch naming system. Thanks for letting me know the old one was broken. 👍🏽 

Also, I've just been testing the `python3-pyopenssl` IPK. 

I have removed the requirement to install this module via Entware, as it appears the one installed via `pip` is working just fine. It's presently at 23.0.0 and I've checked with Medusa, LazyLibrarian and SABnzbd and they all start without issue when using the `pip`-installed one. Naturally, this only applies to new installs. Existing installs would need to uninstall the `python3-pyopenssl` IPK, then restart each of the aforementioned QPKGs so each service-script correctly installs `pyopenssl` from PyPI as-needed inside each apps virtualenv. 

I guess pyOpenSSL presented an issue in the past that I solved by using the precompiled Entware IPK instead of `pip`, but if that is no-longer the case, then great! 🎉

**Comment by rivy** [comment]
> Can I confirm: did you install `cryptography` inside each application's virtualenv, or outside it?
> 
>     * Inside would require you to source each apps `activate` script before running `pip`.
> 
>     * Outside would run the system-wide `pip` available via Entware.

I used the system-wide Entware `pip` (and `pip install openssl>22.1.0` failed [as expected I would guess] when using the system-wide approach).

> Also, what is your NAS model and QTS version please?

Model: QNAP NAS TS-1685
Firmware: QTS 4.4.1.1216

**Comment by rivy** [comment]
> I have removed the requirement to install this module via Entware, as it appears the one installed via `pip` is working just fine. It's presently at 23.0.0 and I've checked with Medusa, LazyLibrarian and SABnzbd and they all start without issue when using the `pip`-installed one. Naturally, this only applies to new installs. Existing installs would need to uninstall the `python3-pyopenssl` IPK, then restart each of the aforementioned QPKGs so each service-script correctly installs `pyopenssl` from PyPI as-needed insed each apps virtualenv.

So `pip uninstall pyopenssl` from the system-wide `pip`, then restart the application(s), correct?

If so, I'll try it on my NAS later tonight.

**Comment by OneCDOnly** [comment]
> So `pip uninstall pyopenssl` from the system-wide `pip`, then restart the application(s), correct?

Correct. And also please uninstall the IPK via Entware:
```
opkg remove python3-pyopenssl
```

**Comment by rivy** [comment]
I've upgraded everything, and it's all working well.
I did have to manually stop  the former SABnzbd process after the SABnzbd upgrade to get it back up, otherwise no hiccups.

All is good.
Thanks again!
