### ISSUE TITLE
Watcher3 not starting daemon

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#47]
Python crash shown in init:
```
-------------------- start requested --------------------
= Sun Jun 21 08:49:41 EST 2020
= daemon is not active
* updating application 'OWatcher3': OK
= result: [0]
= PullGitRepo(): "Already up to date."
* launching: failed!
= result: [1]
= daemon startup messages: "Userdata directory exists, continuing.
Connected to database sqlite:////share/MD0_DATA/.qpkg/OWatcher3/config/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 213, in as_dict
    value = unrepr(value)
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 508, in unrepr
    return b.build(obj)
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 354, in build
    raise TypeError('unrepr does not recognize %s' %
TypeError: unrepr does not recognize 'Constant'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "watcher.py", line 139, in <module>
    root = cherrypy.tree.mount(App(), '{}/'.format(core.URL_BASE), 'core/conf_app.ini')
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cptree.py", line 226, in mount
    app.merge(config)
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cptree.py", line 100, in merge
    _cpconfig.merge(self.config, config)
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/_cpconfig.py", line 139, in merge
    for section, value_map in reprconf.as_dict(other).items():
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 46, in as_dict
    config = Parser().dict_from_file(config)
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 228, in dict_from_file
    return self.as_dict()
  File "/share/MD0_DATA/.qpkg/OWatcher3/OWatcher3/lib/cherrypy/lib/reprconf.py", line 219, in as_dict
    raise ValueError(msg, x.__class__.__name__, x.args)
ValueError: ("Config error in section: '/', option: 'tools.auth.on', value: 'True'. Config values must be valid Python.", 'TypeError', ("unrepr does not recognize 'Constant'",))"
```

**Comment by OneCDOnly** [comment]
This looks like the same traceback generated when attempting to run on Python 3.8.1. Maybe the downgrade to 3.7.4 isn't working?

**Comment by OneCDOnly** [comment]
Here's why: https://github.com/Entware/Entware/issues/491

**Comment by OneCDOnly** [comment]
OK, rough estimate for return of the package archives is 23rd June. :nerd_face:

**Comment by OneCDOnly** [comment]
The 'archive's have returned!
