### ISSUE TITLE
SABnzbd: "Loading" errors after downgrading Python 3.8.3 to 3.7.4

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#73]
SAB UI shows:

![screenshot](https://i.imgur.com/X46kQBz.png)
and main log shows:
```
2020-08-17 05:18:51,759::INFO::[SABnzbd:1136] --------------------------------
2020-08-17 05:18:51,767::INFO::[SABnzbd:1137] SABnzbd.py-3.0.0 (rev=cc465c75543dfa26e3065c7dbf98354d53ad1112)
2020-08-17 05:18:51,770::INFO::[SABnzbd:1138] Full executable path = /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py
2020-08-17 05:18:51,774::INFO::[SABnzbd:1148] Platform = posix
2020-08-17 05:18:51,777::INFO::[SABnzbd:1149] Python-version = 3.7.4 (default, Oct 02 2019, 11:13:20) 
[GCC 7.4.0]
2020-08-17 05:18:51,779::INFO::[SABnzbd:1150] Arguments = "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py" "--daemon" "--browser" "0" "--config-file" "/share/MD0_DATA/.qpkg/SABnzbd/config/config.ini" "--pidfile" "/var/run/SABnzbd.pid"
2020-08-17 05:18:51,781::INFO::[SABnzbd:1154] Not inside a docker container
2020-08-17 05:18:51,783::INFO::[SABnzbd:1157] Preferred encoding = UTF-8
2020-08-17 05:18:51,786::INFO::[SABnzbd:1169] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-08-17 05:18:51,788::INFO::[SABnzbd:1217] Using INI file /share/MD0_DATA/.qpkg/SABnzbd/config/config.ini
2020-08-17 05:18:51,802::ERROR::[__init__:975] Loading /share/MD0_DATA/.qpkg/SABnzbd/config/admin/rss_data.sab failed
2020-08-17 05:18:51,804::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
ValueError: unsupported pickle protocol: 5
2020-08-17 05:18:51,813::ERROR::[__init__:975] Loading /share/MD0_DATA/.qpkg/SABnzbd/config/admin/totals10.sab failed
2020-08-17 05:18:51,815::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
ValueError: unsupported pickle protocol: 5
2020-08-17 05:18:51,997::INFO::[postproc:138] Loading postproc queue
2020-08-17 05:18:52,000::ERROR::[__init__:975] Loading /share/MD0_DATA/.qpkg/SABnzbd/config/admin/postproc2.sab failed
2020-08-17 05:18:52,002::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
ValueError: unsupported pickle protocol: 5
2020-08-17 05:18:52,006::ERROR::[__init__:975] Loading /share/MD0_DATA/.qpkg/SABnzbd/config/admin/queue10.sab failed
2020-08-17 05:18:52,008::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
ValueError: unsupported pickle protocol: 5
2020-08-17 05:18:52,012::ERROR::[__init__:975] Loading /share/MD0_DATA/.qpkg/SABnzbd/config/admin/watched_data2.sab failed
2020-08-17 05:18:52,013::INFO::[__init__:976] Traceback: 
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/sabnzbd/__init__.py", line 965, in load_data
    data = pickle.load(data_file, encoding=sabnzbd.encoding.CODEPAGE)
ValueError: unsupported pickle protocol: 5
2020-08-17 05:18:52,017::INFO::[__init__:955] [N/A] /share/MD0_DATA/.qpkg/SABnzbd/config/admin/Rating.sab missing
2020-08-17 05:18:52,021::INFO::[scheduler:216] Setting schedule for midnight BPS reset
2020-08-17 05:18:52,024::INFO::[__init__:350] All processes started
2020-08-17 05:18:52,027::INFO::[SABnzbd:292] Template location for Glitter is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Glitter
2020-08-17 05:18:52,029::INFO::[SABnzbd:292] Template location for Config is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Config
2020-08-17 05:18:52,087::INFO::[SABnzbd:393] SABYenc module (v4.0.2)... found!
2020-08-17 05:18:52,089::INFO::[SABnzbd:412] Cryptography module (v2.7)... found!
2020-08-17 05:18:52,091::INFO::[SABnzbd:417] par2 binary... found (/usr/bin/par2)
2020-08-17 05:18:52,092::INFO::[SABnzbd:424] UNRAR binary... found (/opt/bin/unrar)
2020-08-17 05:18:52,094::INFO::[SABnzbd:432] UNRAR binary version 5.90
2020-08-17 05:18:52,096::INFO::[SABnzbd:440] 7za binary... found (/opt/bin/7za)
2020-08-17 05:18:52,098::INFO::[SABnzbd:451] nice binary... found (/opt/bin/nice)
2020-08-17 05:18:52,099::INFO::[SABnzbd:455] ionice binary... found (/opt/bin/ionice)
2020-08-17 05:18:52,111::INFO::[SABnzbd:1276] HTTPS keys are OK
2020-08-17 05:18:52,123::INFO::[SABnzbd:1403] Starting web-interface on 0.0.0.0:9195
2020-08-17 05:18:52,125::INFO::[_cplogging:216] [17/Aug/2020:05:18:52] ENGINE Bus STARTING
2020-08-17 05:18:52,370::INFO::[_cplogging:216] [17/Aug/2020:05:18:52] ENGINE Serving on https://0.0.0.0:9195
2020-08-17 05:18:52,485::INFO::[_cplogging:216] [17/Aug/2020:05:18:52] ENGINE Serving on http://0.0.0.0:8900
2020-08-17 05:18:52,486::INFO::[_cplogging:216] [17/Aug/2020:05:18:52] ENGINE Bus STARTED
2020-08-17 05:18:52,490::INFO::[SABnzbd:1440] Starting SABnzbd.py-3.0.0
2020-08-17 05:18:52,493::INFO::[postproc:228] Completed Download Folder /share/Download/complete is not on FAT
2020-08-17 05:18:52,504::INFO::[dirscanner:117] Dirscanner starting up
2020-08-17 05:18:52,522::INFO::[urlgrabber:96] URLGrabber starting up
2020-08-17 05:18:52,959::INFO::[zconfig:71] No Bonjour/ZeroConfig support installed
```

**Comment by OneCDOnly** [comment]
Not downgrading anymore as I've pulled support for Watcher3, so this issue is no-longer.
