### ISSUE TITLE
SABnzbd: "ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1106)"

### ISSUE THREAD

**Issue by OneCDOnly** [OneCDOnly/sherpa#83]
Only happens on first access via SSL (at the same time the browser is throwing a "security risk" error):
```
2020-08-18 08:44:44,638::INFO::[SABnzbd:1136] --------------------------------
2020-08-18 08:44:44,643::INFO::[SABnzbd:1137] SABnzbd.py-3.0.0 (rev=cc465c75543dfa26e3065c7dbf98354d53ad1112)
2020-08-18 08:44:44,646::INFO::[SABnzbd:1138] Full executable path = /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py
2020-08-18 08:44:44,651::INFO::[SABnzbd:1148] Platform = posix
2020-08-18 08:44:44,654::INFO::[SABnzbd:1149] Python-version = 3.8.3 (default, Jun 12 2020, 20:24:48) 
[GCC 8.4.0]
2020-08-18 08:44:44,656::INFO::[SABnzbd:1150] Arguments = "/share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/SABnzbd.py" "--daemon" "--browser" "0" "--config-file" "/share/MD0_DATA/.qpkg/SABnzbd/config/config.ini" "--pidfile" "/var/run/SABnzbd.pid"
2020-08-18 08:44:44,659::INFO::[SABnzbd:1154] Not inside a docker container
2020-08-18 08:44:44,661::INFO::[SABnzbd:1157] Preferred encoding = UTF-8
2020-08-18 08:44:44,663::INFO::[SABnzbd:1169] SSL version = OpenSSL 1.1.1g  21 Apr 2020
2020-08-18 08:44:44,666::INFO::[SABnzbd:1217] Using INI file /share/MD0_DATA/.qpkg/SABnzbd/config/config.ini
2020-08-18 08:44:44,692::INFO::[postproc:138] Loading postproc queue
2020-08-18 08:44:44,700::INFO::[__init__:955] [N/A] /share/MD0_DATA/.qpkg/SABnzbd/config/admin/Rating.sab missing
2020-08-18 08:44:44,705::INFO::[scheduler:216] Setting schedule for midnight BPS reset
2020-08-18 08:44:44,708::INFO::[__init__:350] All processes started
2020-08-18 08:44:44,710::INFO::[SABnzbd:292] Template location for Glitter is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Glitter
2020-08-18 08:44:44,713::INFO::[SABnzbd:292] Template location for Config is /share/MD0_DATA/.qpkg/SABnzbd/SABnzbd/interfaces/Config
2020-08-18 08:44:44,767::INFO::[SABnzbd:393] SABYenc module (v4.0.2)... found!
2020-08-18 08:44:44,769::INFO::[SABnzbd:412] Cryptography module (v2.9.2)... found!
2020-08-18 08:44:44,771::INFO::[SABnzbd:417] par2 binary... found (/usr/bin/par2)
2020-08-18 08:44:44,773::INFO::[SABnzbd:424] UNRAR binary... found (/opt/bin/unrar)
2020-08-18 08:44:44,774::INFO::[SABnzbd:432] UNRAR binary version 5.90
2020-08-18 08:44:44,777::INFO::[SABnzbd:440] 7za binary... found (/opt/bin/7za)
2020-08-18 08:44:44,779::INFO::[SABnzbd:451] nice binary... found (/opt/bin/nice)
2020-08-18 08:44:44,781::INFO::[SABnzbd:455] ionice binary... found (/opt/bin/ionice)
2020-08-18 08:44:46,197::INFO::[misc:752] Self-signed certificates generated successfully
2020-08-18 08:44:46,199::INFO::[SABnzbd:1276] HTTPS keys are OK
2020-08-18 08:44:46,206::INFO::[SABnzbd:1403] Starting web-interface on 0.0.0.0:9195
2020-08-18 08:44:46,207::INFO::[_cplogging:213] [18/Aug/2020:08:44:46] ENGINE Bus STARTING
2020-08-18 08:44:46,396::INFO::[_cplogging:213] [18/Aug/2020:08:44:46] ENGINE Serving on https://0.0.0.0:9195
2020-08-18 08:44:46,503::INFO::[_cplogging:213] [18/Aug/2020:08:44:46] ENGINE Serving on http://0.0.0.0:8900
2020-08-18 08:44:46,505::INFO::[_cplogging:213] [18/Aug/2020:08:44:46] ENGINE Bus STARTED
2020-08-18 08:44:46,508::INFO::[SABnzbd:1440] Starting SABnzbd.py-3.0.0
2020-08-18 08:44:46,511::INFO::[postproc:228] Completed Download Folder /share/Download/complete is not on FAT
2020-08-18 08:44:46,519::INFO::[dirscanner:117] Dirscanner starting up
2020-08-18 08:44:46,522::INFO::[urlgrabber:96] URLGrabber starting up
2020-08-18 08:44:46,680::INFO::[zconfig:71] No Bonjour/ZeroConfig support installed
2020-08-18 08:46:15,725::ERROR::[_cplogging:213] [18/Aug/2020:08:46:15] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 1794, in serve
    self.tick()
  File "/opt/lib/python3.8/site-packages/cheroot/server.py", line 2029, in tick
    conn = self.connections.get_conn(self.socket)
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 188, in get_conn
    return self._from_server_socket(server_socket)
  File "/opt/lib/python3.8/site-packages/cheroot/connections.py", line 207, in _from_server_socket
    s, ssl_env = self.server.ssl_adapter.wrap(s)
  File "/opt/lib/python3.8/site-packages/cheroot/ssl/builtin.py", line 277, in wrap
    s = self.context.wrap_socket(
  File "/opt/lib/python3.8/ssl.py", line 500, in wrap_socket
  File "/opt/lib/python3.8/ssl.py", line 1040, in _create
  File "/opt/lib/python3.8/ssl.py", line 1309, in do_handshake
ssl.SSLError: [SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate (_ssl.c:1106)
```
Subsequent access is fine. 

Also, after restarting SABnzbd:
```
2020-08-18 08:49:44,138::INFO::[SABnzbd:455] ionice binary... found (/opt/bin/ionice)
2020-08-18 08:49:44,151::INFO::[SABnzbd:1276] HTTPS keys are OK
2020-08-18 08:49:44,160::INFO::[SABnzbd:1403] Starting web-interface on 0.0.0.0:9195
```
... so same keys as last time. But this time, no problem. 😕

**Comment by Safihre** [comment]
This is a different one than `Error 0` and depends on what browser you use, I think this one is specific to Firefox. I thought this one was ignored by `cheroot` but guess they removed that.
In any case, nothing to worry about. False positive error :)

**Comment by OneCDOnly** [comment]
@Safihre thank you, I'll close this issue. 

Cheers mate! 😄
